services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    command: streamlit run app.py --server.port 8501
    volumes: ['./front:/app']
    restart: unless-stopped
    env_file:
      - .env
    ports:
        - 8501:8501

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
volumes:
  qdrant_data:
